#!/usr/local/bin/python3
MYSQL = {
    'host': '127.0.0.1',
    'user': 'root',
    'password': 'root',
    'db': 'comment',
    'port': '3306',
    'charset': 'utf8',
}

LOG = {
    'MySql': 'mysql/error.log',
    'Driver': 'driver/error.log',
    'Request': 'request/error.log',
    'Soup': 'soup/error.log'
}

url_list = ['http://price.zol.com.cn/',
            'http://mobile.zol.com.cn/',
            'http://mobile.zol.com.cn/iphone.html',
            'http://mobile.zol.com.cn/soc/',
            'http://4g.zol.com.cn/', 'http://5g.zol.com.cn/',
            'http://smartwear.zol.com.cn/',
            'http://mobile.zol.com.cn/chaiji.html',
            'http://nb.zol.com.cn/yxb/',
            'http://pad.zol.com.cn/',
            'http://pc.zol.com.cn/',
            'http://aio.zol.com.cn/',
            'http://robot.zol.com.cn/',
            'http://nb.zol.com.cn/portable.html',
            'http://lcd.zol.com.cn/vr.html',
            'http://diy.zol.com.cn/',
            'http://cpu.zol.com.cn/',
            'http://vga.zol.com.cn/',
            'http://lcd.zol.com.cn/',
            'http://mouse.zol.com.cn/',
            'http://mb.zol.com.cn/',
            'http://ssd.zol.com.cn/',
            'http://memory.zol.com.cn/',
            'http://bi.zol.com.cn/',
            'http://power.zol.com.cn/',
            'http://esports.zol.com.cn/',
            'http://dcdv.zol.com.cn/',
            'http://lasertv.zol.com.cn/',
            'http://sound.zol.com.cn/',
            'http://headphone.zol.com.cn/',
            'http://mouse.zol.com.cn/',
            'http://display.zol.com.cn/',
            'http://dcdv.zol.com.cn/travel.html',
            'http://oled.zol.com.cn/',
            'http://jd.zol.com.cn/',
            'http://tv.zol.com.cn/',
            'http://icebox.zol.com.cn/',
            'http://life.zol.com.cn/',
            'http://washer.zol.com.cn/',
            'http://ac.zol.com.cn/',
            'http://jd.zol.com.cn/category_52.html',
            'http://hd.zol.com.cn/',
            'http://air.zol.com.cn/',
            'http://water.zol.com.cn/',
            'http://sh.zol.com.cn/',
            'http://biz.zol.com.cn/',
            'http://oa.zol.com.cn/',
            'http://oa.zol.com.cn/printer.html',
            'http://projector.zol.com.cn/',
            'http://net.zol.com.cn/',
            'http://projector.zol.com.cn/movie.html',
            'http://server.zol.com.cn/',
            'http://teach.zol.com.cn/',
            'http://health.zol.com.cn/',
            'http://cloud.zol.com.cn/',
            'http://auto.zol.com.cn/',
            'http://geek.zol.com.cn/',
            'http://ebike.zol.com.cn/',
            'http://ai.zol.com.cn/',
            'http://gps.zol.com.cn/',
            'http://3dp.zol.com.cn/',
            'http://chepin.zol.com.cn/',
            'http://lock.zol.com.cn/']
